### PR TITLE
only inferring a single image frame once for a huge performance boost

### PR DESCRIPTION
**Pull request by zoombinis**
When I first used darknet_ros, I discovered a single image frame from a video camera was being used as the same input for inference redundantly up to 70 times on my NVidia Quadro RTX 3000!

So to use far less processing resources unnecessarily, this PR simply keeps track of the last consumed image frame ID to ensure it doesn't infer with it again.

### CODE REVIEW

**Comment by zoombinis** [comment]
This resolves these issues:
https://github.com/leggedrobotics/darknet_ros/issues/150
https://github.com/ZhiangChen/target_mapping/issues/8

**Comment by tomlankhorst** [comment]
Thanks for your contribution.

**Comment by tomlankhorst** [comment]
Can you rebase on upstream master? I've added GitHub actions so that you can see what the tests do.

**Comment by tomlankhorst** [comment]
Accidentally closed this PR... reopened as #301

**Pull request closed without merging**
